# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define Etc.getlogin + ".pokegen.com"
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.56.200"
  config.vm.synced_folder "../", "/var/www/pokegen", owner: "www-data"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "pokegen"
    vb.memory = 1024
    vb.gui    = false
    vb.cpus   = 2
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/vagrant.yml"
    ansible.groups = {
      "vagrant" => [Etc.getlogin + ".pokegen.com"],
    }
  end
end
